config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  get 'profile', to: 'profile#dashboard', as: :profile
  scope '/profile' do
    get 'upgrade', to: 'profile#upgrade_form'
    post 'upgrade', to: 'profile#upgrade'
  end

  get 'about', to: 'welcome#about', as: :about
  get 'services', to: 'welcome#services', as: :services
  get 'contact', to: 'welcome#contact', as: :contact
  get 'stream', to: 'welcome#stream', as: :stream
  get 'privacy', to: 'welcome#privacy', as: :privacy

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :articles, only: [:index, :show]

  resources :testimonials, except: [:show]

  resources :appointments


  namespace :admin do
    resources :articles do
      post 'toggle', to: 'articles#toggle', param: :id
    end

    resources :testimonials, only: [:index] do
      post 'toggle', to: 'testimonials#toggle', param: :id
    end

    get 'stream', to: 'stream_codes#index', as: :stream
    post 'stream/update', to: 'stream_codes#update', as: :stream_update
  end

  
end

app/models/User/admin.rb
class User::Admin < User

    def test_qq
        "ff"
    end
end

app/models/User/member.rb
class User::Member < User
end

app/models/User/subscriber.rb
class User::Subscriber < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
end

app/models/article.rb
class Article < ApplicationRecord
  has_rich_text :content

  @@preview_end_keyword = '^PREVIEW^'

  def preview
    source = content.body.fragment.source

    paywall_article = false
    preview_end = 0

    source.children.each_with_index do |child, index|
      if child.text.include? @@preview_end_keyword 
        paywall_article = true
        preview_end = index
        child.traverse do |n|
          if n.text?
            n.content = n.content.gsub @@preview_end_keyword, ''
          end
        end
      end
    end

    if paywall_article
      content.body.fragment.source.children = source.children[0..preview_end]
    end

    content
  end

end

app/models/stream_codes.rb
class StreamCodes < ApplicationRecord
end

app/models/testimonial.rb
class Testimonial < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise :omniauthable, omniauth_providers: %i[facebook]

  has_many :testimonials

  enum type: [
    'User::Admin',
    'User::Member',
    'User::Subscriber'
  ]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name   # assuming the user model has a name

    end
  end

  def customer_id
    JSON.parse(customer_info)['id'] if customer_info.present?
  end

  def cc
    JSON.parse(card_info)
  end

end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::AdminController

    def index
        @articles = Article.all
        render layout: 'layouts/admin'
    end

    def edit
        @article = Article.find(params[:id])
        render layout: 'layouts/admin'
    end

    def update
        Article.update params[:id], params.require(:article).permit(:title, :content, :subtitle, :premium)
        redirect_to :admin_articles
    end

    def new
        @article = Article.new
        render layout: 'layouts/admin'
    end

    def create
        article = Article.create! params.require(:article).permit(:title, :content, :subtitle, :premium)
        redirect_to :admin_articles
    end

    def toggle
        article = Article.find(params[:article_id]).toggle!(:hidden)

        redirect_to :admin_articles
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController


    def index
    end

    def create
    end

    def new
    end

    def edit
    end

    def show
    end

    def update
    end

    def destroy
    end
    

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    def index
        @articles = Article.where(hidden: false)
    end

    def show
        @article = Article.find(params[:id])

        # User clicked on a premium article
        if @article.premium
            # Direct them to user registration if they are not signed in
            unless user_signed_in?
                flash[:alert] = "Sign in to your premium account to view the full article"
                redirect_to :new_user_session
                return
            end

            # TODO: If they are logged in but not a member, redirect to User type control panel
            if current_user.type == 'User::Subscriber'
                flash[:alert] = "This is a premium members only article - please purchase a membership to read the whole article"
                redirect_to :root
            end
        end

    end
    
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
    before_action :authenticate_user!
    skip_before_action :verify_authenticity_token

    def dashboard
    end

    def upgrade_form
        redirect_to :profile if current_user.type == 'User::Member' 
    end

    # Post
    def upgrade
        user = current_user

        customer = {
            name: user.name,
            email_address: user.email
        }

        card = {
            billing_address: {
                address_line_1: params[:address_line_1],
                address_line_2: params[:address_line_2],
                locality: params[:locality],
                administrative_district_level_1: params[:administrative_district_level_1],
                postal_code: params[:postal_code],
                country: params[:country],
            },
            cardholder_name: params[:cardholder_name],
            card_nonce: params[:nonce]
        }
        
        # { customer_info: json, card_info: json }
        customer_data = Membership::Premium.upgrade_user(customer, card)
        
        user.update(customer_data)

        render json: { success: true, message: 'Membership Enrollment Successful' }
    rescue => e
        render json: { success: false, message: e.message }
    end
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @testimonials = Testimonial.where(visible: true)
  end

  def create
    Testimonial.create(content: params[:content], visible: false, user_id: current_user.id)

    flash[:alert] = "Thank you for posting a testimonial! Look for it up on the Testimonials page sometime soon!"
    redirect_to :root
  end

  def new
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    before_action :authenticate_member, only: :stream

    def index
        if signed_in?
            @user = current_user
        end

        @show_modal = true unless session[:cookies_confirm]

        session[:cookies_confirm] = true

    end
    
    def services
    end

    def about
    end

    def privacy

    end

    def contact
    end

    def stream
        @video_url = StreamCodes.last&.code
    end
    

    def authenticate_member
        return redirect_to new_user_session_path unless signed_in?

        unless ['User::Admin', 'User::Member'].include?(current_user.type)
            flash[:alert] = "You must be a member to view the live stream"
            redirect_to :root
        end
    end

end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
    def user_type(user)
        user.type.split('::')[1].capitalize
    end
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/articles/_form.html.erb
<h3><%= title %></h3>

<%= form_with(model: article, url: path) do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle, class: "form-control" %>
  </div>
  <div class="form-check">
    <%= form.check_box :premium, class: "form-check-input" %>
    <%= form.label :premium, 'Premium Article?', class: "form-check-label" %>
  </div>
  <br>
  <div class="form-group">
    <%= form.rich_text_area :content %>
  </div>

  <%= form.submit %>
<% end %>

app/views/admin/articles/edit.html.erb
<%= render 'admin/articles/form', article: @article, title: 'Edit Article', path: admin_article_path %>

app/views/admin/articles/index.html.erb
<%= link_to 'New Article', new_admin_article_path %>
<br>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Title</th>
      <th scope="col">Premium?</th>
      <th scope="col">Date Posted</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>

    <% @articles.each do |article| %>
      <tr <%= 'class="text-muted"'.html_safe if article.hidden %>>
        <td><%= article.id %></td>
        <td><%= article.title %></td>
        <td><%= article.premium ? 'Yes' : 'No' %></td>
        <td><%= article.created_at.strftime('%F') %></td>
        <td>
          <%= link_to 'Edit', edit_admin_article_path(article.id), class: "btn btn-secondary btn-sm" %> 
          <%= link_to 'Show/Hide', admin_article_toggle_path(article.id), method: :post, class: "btn btn-secondary btn-sm" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/articles/new.html.erb
<%= render 'admin/articles/form', article: @article, title: 'New Article', path: admin_articles_path %>

app/views/articles/index.html.erb
<h3 class="ml-5 mb-2">Articles</h3>

<% if @articles.empty? %>
No articles yet!

<% else %>

<%= render partial: 'layouts/articles/preview', collection: @articles %>

<% end %>

app/views/articles/show.html.erb
<h1 class="ml-5 mb-2"><%= @article.title %><br>
<small class="ml-5 mb-2"><%= @article.subtitle %>
</h1>

<%= @article.content %>

app/views/layouts/articles/_preview.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title">
      <%= preview.title %><br>
      <small class="text-muted"><%= preview.subtitle %></small>
    </h5>

    <p class="card-text"><%= preview.preview %></p>
  </div>
  <div class="card-footer">
    <%= link_to 'Read more', article_path(preview.id)%>
  </div>
</div>
<br>