config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  get 'profile', to: 'profile#dashboard', as: :profile
  scope '/profile' do
    get 'upgrade', to: 'profile#upgrade_form'
    post 'upgrade', to: 'profile#upgrade'
  end

  get 'about', to: 'welcome#about', as: :about
  get 'services', to: 'welcome#services', as: :services
  get 'contact', to: 'welcome#contact', as: :contact
  get 'stream', to: 'welcome#stream', as: :stream
  get 'privacy', to: 'welcome#privacy', as: :privacy

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :articles, only: [:index, :show]

  resources :testimonials, except: [:show]

  resources :appointments


  namespace :admin do
    resources :articles do
      post 'toggle', to: 'articles#toggle', param: :id
    end

    resources :testimonials, only: [:index] do
      post 'toggle', to: 'testimonials#toggle', param: :id
    end

    get 'stream', to: 'stream_codes#index', as: :stream
    post 'stream/update', to: 'stream_codes#update', as: :stream_update
  end

  
end

app/models/User/admin.rb
class User::Admin < User

    def test_qq
        "ff"
    end
end

app/models/User/member.rb
class User::Member < User
end

app/models/User/subscriber.rb
class User::Subscriber < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
end

app/models/article.rb
class Article < ApplicationRecord
  has_rich_text :content

  @@preview_end_keyword = '^PREVIEW^'

  def preview
    source = content.body.fragment.source

    paywall_article = false
    preview_end = 0

    source.children.each_with_index do |child, index|
      if child.text.include? @@preview_end_keyword 
        paywall_article = true
        preview_end = index
        child.traverse do |n|
          if n.text?
            n.content = n.content.gsub @@preview_end_keyword, ''
          end
        end
      end
    end

    if paywall_article
      content.body.fragment.source.children = source.children[0..preview_end]
    end

    content
  end

end

app/models/stream_codes.rb
class StreamCodes < ApplicationRecord
end

app/models/testimonial.rb
class Testimonial < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise :omniauthable, omniauth_providers: %i[facebook]

  has_many :testimonials

  enum type: [
    'User::Admin',
    'User::Member',
    'User::Subscriber'
  ]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name   # assuming the user model has a name

    end
  end

  def customer_id
    JSON.parse(customer_info)['id'] if customer_info.present?
  end

  def cc
    JSON.parse(card_info)
  end

end

app/controllers/admin/testimonials_controller.rb
class Admin::TestimonialsController <  Admin::AdminController
  def index
    @testimonials = Testimonial.all
    render layout: 'layouts/admin'
  end

  def toggle
    Testimonial.find(params[:testimonial_id]).toggle!(:visible)

    redirect_to :admin_testimonials
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController


    def index
    end

    def create
    end

    def new
    end

    def edit
    end

    def show
    end

    def update
    end

    def destroy
    end
    

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    def index
        @articles = Article.where(hidden: false)
    end

    def show
        @article = Article.find(params[:id])

        # User clicked on a premium article
        if @article.premium
            # Direct them to user registration if they are not signed in
            unless user_signed_in?
                flash[:alert] = "Sign in to your premium account to view the full article"
                redirect_to :new_user_session
                return
            end

            # TODO: If they are logged in but not a member, redirect to User type control panel
            if current_user.type == 'User::Subscriber'
                flash[:alert] = "This is a premium members only article - please purchase a membership to read the whole article"
                redirect_to :root
            end
        end

    end
    
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
    before_action :authenticate_user!
    skip_before_action :verify_authenticity_token

    def dashboard
    end

    def upgrade_form
        redirect_to :profile if current_user.type == 'User::Member' 
    end

    # Post
    def upgrade
        user = current_user

        customer = {
            name: user.name,
            email_address: user.email
        }

        card = {
            billing_address: {
                address_line_1: params[:address_line_1],
                address_line_2: params[:address_line_2],
                locality: params[:locality],
                administrative_district_level_1: params[:administrative_district_level_1],
                postal_code: params[:postal_code],
                country: params[:country],
            },
            cardholder_name: params[:cardholder_name],
            card_nonce: params[:nonce]
        }
        
        # { customer_info: json, card_info: json }
        customer_data = Membership::Premium.upgrade_user(customer, card)
        
        user.update(customer_data)

        render json: { success: true, message: 'Membership Enrollment Successful' }
    rescue => e
        render json: { success: false, message: e.message }
    end
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @testimonials = Testimonial.where(visible: true)
  end

  def create
    Testimonial.create(content: params[:content], visible: false, user_id: current_user.id)

    flash[:alert] = "Thank you for posting a testimonial! Look for it up on the Testimonials page sometime soon!"
    redirect_to :root
  end

  def new
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    before_action :authenticate_member, only: :stream

    def index
        if signed_in?
            @user = current_user
        end

        @show_modal = true unless session[:cookies_confirm]

        session[:cookies_confirm] = true

    end
    
    def services
    end

    def about
    end

    def privacy

    end

    def contact
    end

    def stream
        @video_url = StreamCodes.last&.code
    end
    

    def authenticate_member
        return redirect_to new_user_session_path unless signed_in?

        unless ['User::Admin', 'User::Member'].include?(current_user.type)
            flash[:alert] = "You must be a member to view the live stream"
            redirect_to :root
        end
    end

end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper
end

app/helpers/admin/testimonials_helper.rb
module Admin::TestimonialsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
    def user_type(user)
        user.type.split('::')[1].capitalize
    end
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/testimonials/index.html.erb
<br>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">User</th>
      <th scope="col">Content</th>
      <th scope="col">Visible?</th>
      <th scope="col">Date Posted</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>

    <% @testimonials.each do |testimonial| %>
      <tr <%= 'class="text-muted"'.html_safe unless testimonial.visible %>>
        <td><%= testimonial.id %></td>
        <td><%= testimonial.user.name || testimonial.user.email %></td>
        <td><%= testimonial.content %></td>
        <td><%= testimonial.visible ? 'Yes' : 'No' %></td>
        <td><%= testimonial.created_at.strftime('%D') %></td>
        <td>
          <%= link_to 'Show/Hide', admin_testimonial_toggle_path(testimonial.id), method: :post, class: "btn btn-secondary btn-sm" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/testimonials/index.html.erb
<div class="testimonial-container">
<div class="tes-header">
<h1>Testimonials</h1>

<button class="btn btn-secondary"><%= link_to 'Post Testimonial', new_testimonial_path %></button>

</div>
<% if @testimonials.count > 0 %>

  <% @testimonials.each do |testimonial| %>

    <div class="testimonial">
      <p><%= testimonial.content %></p>
      <p class="tes-date">Posted <%= testimonial.created_at.strftime('%D') %> <%= "by #{testimonial.user.name}" if testimonial.user.name.present? %></p>
    </div>

    <br>
    <hr/>

    <br>
  <% end %>

<% else %>

  No Testimonials Posted Yet! Click <%= link_to 'here', new_testimonial_path %> to post the first one!


<% end %>

</div>

app/views/testimonials/new.html.erb
<%= form_with(url: testimonials_path, method: "post") do %>
    <h2>New Testimonial</h2>
    <div class="form-group">
        <label for="content" class="control-label">Leave a short message about your experience with Compassionate Wings</label>
        <textarea class="form-control" id="content" name="content" rows="5"></textarea>
    </div>
<%= submit_tag("Submit") %>
<% end %>