config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  get 'profile', to: 'profile#dashboard', as: :profile
  scope '/profile' do
    get 'upgrade', to: 'profile#upgrade_form'
    post 'upgrade', to: 'profile#upgrade'
  end

  get 'about', to: 'welcome#about', as: :about
  get 'services', to: 'welcome#services', as: :services
  get 'contact', to: 'welcome#contact', as: :contact
  get 'stream', to: 'welcome#stream', as: :stream
  get 'privacy', to: 'welcome#privacy', as: :privacy

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :articles, only: [:index, :show]

  resources :testimonials, except: [:show]

  resources :appointments


  namespace :admin do
    resources :articles do
      post 'toggle', to: 'articles#toggle', param: :id
    end

    resources :testimonials, only: [:index] do
      post 'toggle', to: 'testimonials#toggle', param: :id
    end

    get 'stream', to: 'stream_codes#index', as: :stream
    post 'stream/update', to: 'stream_codes#update', as: :stream_update
  end

  
end

app/models/User/admin.rb
class User::Admin < User

    def test_qq
        "ff"
    end
end

app/models/User/member.rb
class User::Member < User
end

app/models/User/subscriber.rb
class User::Subscriber < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
end

app/models/article.rb
class Article < ApplicationRecord
  has_rich_text :content

  @@preview_end_keyword = '^PREVIEW^'

  def preview
    source = content.body.fragment.source

    paywall_article = false
    preview_end = 0

    source.children.each_with_index do |child, index|
      if child.text.include? @@preview_end_keyword 
        paywall_article = true
        preview_end = index
        child.traverse do |n|
          if n.text?
            n.content = n.content.gsub @@preview_end_keyword, ''
          end
        end
      end
    end

    if paywall_article
      content.body.fragment.source.children = source.children[0..preview_end]
    end

    content
  end

end

app/models/stream_codes.rb
class StreamCodes < ApplicationRecord
end

app/models/testimonial.rb
class Testimonial < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise :omniauthable, omniauth_providers: %i[facebook]

  has_many :testimonials

  enum type: [
    'User::Admin',
    'User::Member',
    'User::Subscriber'
  ]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name   # assuming the user model has a name

    end
  end

  def customer_id
    JSON.parse(customer_info)['id'] if customer_info.present?
  end

  def cc
    JSON.parse(card_info)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController


    def index
    end

    def create
    end

    def new
    end

    def edit
    end

    def show
    end

    def update
    end

    def destroy
    end
    

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    def index
        @articles = Article.where(hidden: false)
    end

    def show
        @article = Article.find(params[:id])

        # User clicked on a premium article
        if @article.premium
            # Direct them to user registration if they are not signed in
            unless user_signed_in?
                flash[:alert] = "Sign in to your premium account to view the full article"
                redirect_to :new_user_session
                return
            end

            # TODO: If they are logged in but not a member, redirect to User type control panel
            if current_user.type == 'User::Subscriber'
                flash[:alert] = "This is a premium members only article - please purchase a membership to read the whole article"
                redirect_to :root
            end
        end

    end
    
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
    before_action :authenticate_user!
    skip_before_action :verify_authenticity_token

    def dashboard
    end

    def upgrade_form
        redirect_to :profile if current_user.type == 'User::Member' 
    end

    # Post
    def upgrade
        user = current_user

        customer = {
            name: user.name,
            email_address: user.email
        }

        card = {
            billing_address: {
                address_line_1: params[:address_line_1],
                address_line_2: params[:address_line_2],
                locality: params[:locality],
                administrative_district_level_1: params[:administrative_district_level_1],
                postal_code: params[:postal_code],
                country: params[:country],
            },
            cardholder_name: params[:cardholder_name],
            card_nonce: params[:nonce]
        }
        
        # { customer_info: json, card_info: json }
        customer_data = Membership::Premium.upgrade_user(customer, card)
        
        user.update(customer_data)

        render json: { success: true, message: 'Membership Enrollment Successful' }
    rescue => e
        render json: { success: false, message: e.message }
    end
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @testimonials = Testimonial.where(visible: true)
  end

  def create
    Testimonial.create(content: params[:content], visible: false, user_id: current_user.id)

    flash[:alert] = "Thank you for posting a testimonial! Look for it up on the Testimonials page sometime soon!"
    redirect_to :root
  end

  def new
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    before_action :authenticate_member, only: :stream

    def index
        if signed_in?
            @user = current_user
        end

        @show_modal = true unless session[:cookies_confirm]

        session[:cookies_confirm] = true

    end
    
    def services
    end

    def about
    end

    def privacy

    end

    def contact
    end

    def stream
        @video_url = StreamCodes.last&.code
    end
    

    def authenticate_member
        return redirect_to new_user_session_path unless signed_in?

        unless ['User::Admin', 'User::Member'].include?(current_user.type)
            flash[:alert] = "You must be a member to view the live stream"
            redirect_to :root
        end
    end

end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
    def user_type(user)
        user.type.split('::')[1].capitalize
    end
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<div class="row justify-content-around">
<div class="col-3">
       
    <!-#space holder->
</div>
    <div class="col-3">
    <label class="sub-pg">About Us</label>
        <p id="as-des">
            Connecting you to loved ones and giving guidance in the right direction to your future. I am here
            to discover what potentially has you blocked.
        </p>
        <br>
        <p id="as-des">
        Contact me or make an appointment to book your spiritual consultation.
        </p>
        <br>
        <p id="as-des">
        Phone: 613-793-3370
        </p>
        <p>
        <a href="RealPsychicandSpiritualMedium@outlook.com">eMail Us</a> 
        
         <a href="www.facebook.com/CompassionateWingsMindBodySoul/?ref=page_internal">Facebook</a>
        </p>

    </div>
   
    <div class="col-3">
    <div id="as-crousel" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100" src="/images/about_us/Anne_1.jpg" alt="First slide">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="/images/about_us/Anne_3.jpg" alt="Second slide">
      </div>
      <div class="carousel-item ">
        <img class="d-block w-100" src="/images/about_us/Anne_4.jpg" alt="Third slide">
      </div>
      <div class="carousel-item ">
        <img class="d-block w-100" src="/images/about_us/Anne_5.jpg" alt="Third slide">
      </div>
      <div class="carousel-item ">
        <img class="d-block w-100" src="/images/about_us/Anne_6.jpg" alt="Third slide">
      </div>
      <div class="carousel-item ">
        <img class="d-block w-100" src="/images/about_us/Anne_7.jpg" alt="Third slide">
      </div>
      <div class="carousel-item ">
        <img class="d-block w-100" src="/images/about_us/Anne_8.jpg" alt="Third slide">
      </div>
      <div class="carousel-item ">
        <img class="d-block w-100" src="/images/about_us/Anne_9.jpg" alt="Third slide">
      </div>
      <div class="carousel-item ">
        <img class="d-block w-100" src="/images/about_us/Anne_10.jpg" alt="Third slide">
      </div>
    </div>
  </div>

    </div>
    <div class="col-3">
    <!-#space holder->

    </div>
</div>

app/views/welcome/contact.html.erb
Contact information

app/views/welcome/index.html.erb
<% content_for :navbar do %>
    <%= render 'layouts/navbar' %>
<% end %>

<% # binding.pry %>




<div class="row d-flex justify-content-around home-sub-grids"
style="margin-left: 1vw;">
  <div class="col-xs-6 col-md-4">
    <a href="#" class="thumbnail">
      <img src="/images/articles.jpg" alt="...">
    </a>
    <p>


<h2>Articles</h2>
<%= link_to 'All Articles', articles_path %><br>
</p>
  </div>
  
  <div class="col-xs-6 col-md-4">
    <a href="#" class="thumbnail">

      <img src="/images/testimonies.jpg" alt="...">

    </a>
    <p>
<h2>Testimonies</h2>
    <%= link_to 'All Testimonials', testimonials_path %>
</p>
  </div>

  <div class="col-xs-6 col-md-4">
    <a href="#" class="thumbnail">

      <img src="/images/appointments.jpg" alt="...">

    </a>
    <p>
<h2>Appointments</h2>
<%= link_to 'Appointments', 'https://www.facebook.com/pg/CompassionateWingsMindBodySoul/services/?ref=page_internal' %><br>
  </div>

</div>


<% if @show_modal %>

  <div id='cookies' class="modal" tabindex="-1" role="dialog" style="color: black">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Attention</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>This site uses cookies. Remaining on this site will be considered consent</p>
          <p><%= link_to 'Privacy Policy', privacy_path %></p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

  <% content_for :scripts do %>
    $('#cookies').modal('show')

  <% end %>

<% end %>

app/views/welcome/privacy.html.erb
<h1>Privacy Notice</h1>
<p>
This privacy notice discloses the privacy practices for (website address). This privacy notice applies solely to information collected by this website. It will notify you of the following:
</p>

<ul>
  <li>What personally identifiable information is collected from you through the website, how it is used and with whom it may be shared.</li>
  <li>What choices are available to you regarding the use of your data.</li>
  <li>The security procedures in place to protect the misuse of your information.</li>
  <li>How you can correct any inaccuracies in the information.</li>

</ul>

<h4>Information Collection, Use, and Sharing</h4>
<p>
We are the sole owners of the information collected on this site. We only have access to/collect information that you voluntarily give us via email or other direct contact from you. We will not sell or rent this information to anyone.
</p>

<p>
We will use your information to respond to you, regarding the reason you contacted us. We will not share your information with any third party outside of our organization, other than as necessary to fulfill your request, e.g. to ship an order.
</p>

<p>
Unless you ask us not to, we may contact you via email in the future to tell you about specials, new products or services, or changes to this privacy policy.
</p>

<h4>Your Access to and Control Over Information</h4>
<p>
You may opt out of any future contacts from us at any time. You can do the following at any time by contacting us via the email address or phone number given on our website:
</p>

<ul>
  <li>See what data we have about you, if any.</li>
  <li>Change/correct any data we have about you.</li>
  <li>Have us delete any data we have about you.</li>
  <li>Express any concern you have about our use of your data.</li>
</ul>

<h4>Security</h4>
<p>
We take precautions to protect your information. When you submit sensitive information via the website, your information is protected both online and offline.
</p>

<p>
Wherever we collect sensitive information (such as credit card data), that information is encrypted and transmitted to us in a secure way. You can verify this by looking for a lock icon in the address bar and looking for "https" at the beginning of the address of the Web page.
</p>

<p>
While we use encryption to protect sensitive information transmitted online, we also protect your information offline. Only employees who need the information to perform a specific job (for example, billing or customer service) are granted access to personally identifiable information. The computers/servers in which we store personally identifiable information are kept in a secure environment.
</p>

<p>
We request information from you on our order form. To buy from us, you must provide contact information (like name and shipping address) and financial information (like credit card number, expiration date). This information is used for billing purposes and to fill your orders. If we have trouble processing an order, we'll use this information to contact you.
</p>

<p>
We use "cookies" on this site. A cookie is a piece of data stored on a site visitor's hard drive to help us improve your access to our site and identify repeat visitors to our site. For instance, when we use a cookie to identify you, you would not have to log in a password more than once, thereby saving time while on our site. Cookies can also enable us to track and target the interests of our users to enhance the experience on our site. Usage of a cookie is in no way linked to any personally identifiable information on our site.
</p>

<p>
This website contains links to other sites. Please be aware that we are not responsible for the content or privacy practices of such other sites. We encourage our users to be aware when they leave our site and to read the privacy statements of any other site that collects personally identifiable information.
</p>

<p>
If you feel that we are not abiding by this privacy policy, you should contact us immediately via telephone at XXX YYY-ZZZZ or via email.
</p>

app/views/welcome/services.html.erb
<div class="service-container" style="background-color:rgb(11,11,11,.1); width:85%; margin:auto; padding:4rem">
<h2>Services</h2>
<p>
Missing Person - 30 minutes - Price Varies
</p>
<p>
Do you have a missing persons case? I can help. I have had many cases where a missing
person was involved.
</p>
<p>
Spiritual Reading - 1 hour - $125.00
</p>
<p>
- ½ hour - $80.00
</p>
<p>
Love, luck, career, present, past and future. Spirit readings advise on all matters of life and
answers all your personal questions.
</p>
<p>
Mediumship Session - ½ hour - $125.00
</p>
<p>
Connecting with your loved ones that passed on to receive messages and receive closure.
</p>
<p>
Pendulum Reading - Duration varies - Starts from $20.00
</p>
<p>
Ask 5 questions and receive answers through divination.
</p>
<p>
Life Coach - 1 hour - $120.00
</p>
<p>
Guidance and help with releasing past trauma. Self-esteem building and figuring out what a

healthy partner is.
</p>
<p>
Relaxation Massage/Deep Tissue Massage - $80.00
</p>
<p>
Membership Page
<p>
** ALL paying members have access to premium articles and videos
</p>
<p>
** No Cancellations
</p>
<p>
Bronze VIP Membership - 3 Months - $300.00
</p>
<p>
- 6 months - $500.00
</p>
<p>
Includes 1 Full Reading and 1 Pendulum Reading each month
</p>
<p>
Silver VIP Membership - 3 months - $450.00
</p>
<p>
- 6 months - $800.00
</p>
<p>
Includes 1 Full Reading, 2 Mini Readings, and 1 Pendulum Reading each month
</p>
<p>
Gold VIP Membership - 3 Months - $450.00
</p>
<p>
- 6 months - $1000.00
</p>
<p>
Includes 2 Full Readings, 2 Mini Readings, and 2 Pendulum Readings each month
</p>
<p>
Ultimate VIP Membership - 3 Months - $750.00
</p>
<p>
- 6 months - $1300.00
</p>
<p>
Includes 4 Full readings, 4 Pendulum Readings, Private Messaging with Anne, and 4 Spiritual
Therapy.
</p>
</div>

app/views/welcome/stream.html.erb
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v4.0&appId=<%= ENV['FB_APP_ID'] %>&autoLogAppEvents=1"></script>

<div class='text-center'>
    <div 
        
        class="fb-video" 
        data-href="https://www.facebook.com/facebook/videos/<%= @video_url %>/" 
        data-width="900" 
        data-show-text="false"
        data-allowfullscreen="true"
        >

<blockquote cite="https://developers.facebook.com/facebook/videos/<%= @video_url %>/" class="fb-xfbml-parse-ignore">
<a href="https://developers.facebook.com/facebook/videos/<%= @video_url %>/">How to Share With Just Friends</a>
<p>How to share with just friends.</p>
Posted by <a href="https://www.facebook.com/facebook/">Facebook</a> on Friday, 5 December 2014</blockquote>
        
    </div>
</div>