config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  get 'profile', to: 'profile#dashboard', as: :profile
  scope '/profile' do
    get 'upgrade', to: 'profile#upgrade_form'
    post 'upgrade', to: 'profile#upgrade'
  end

  get 'about', to: 'welcome#about', as: :about
  get 'services', to: 'welcome#services', as: :services
  get 'contact', to: 'welcome#contact', as: :contact
  get 'stream', to: 'welcome#stream', as: :stream
  get 'privacy', to: 'welcome#privacy', as: :privacy

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :articles, only: [:index, :show]

  resources :testimonials, except: [:show]

  resources :appointments


  namespace :admin do
    resources :articles do
      post 'toggle', to: 'articles#toggle', param: :id
    end

    resources :testimonials, only: [:index] do
      post 'toggle', to: 'testimonials#toggle', param: :id
    end

    get 'stream', to: 'stream_codes#index', as: :stream
    post 'stream/update', to: 'stream_codes#update', as: :stream_update
  end

  
end

app/models/User/admin.rb
class User::Admin < User

    def test_qq
        "ff"
    end
end

app/models/User/member.rb
class User::Member < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
end

app/models/article.rb
class Article < ApplicationRecord
  has_rich_text :content

  @@preview_end_keyword = '^PREVIEW^'

  def preview
    source = content.body.fragment.source

    paywall_article = false
    preview_end = 0

    source.children.each_with_index do |child, index|
      if child.text.include? @@preview_end_keyword 
        paywall_article = true
        preview_end = index
        child.traverse do |n|
          if n.text?
            n.content = n.content.gsub @@preview_end_keyword, ''
          end
        end
      end
    end

    if paywall_article
      content.body.fragment.source.children = source.children[0..preview_end]
    end

    content
  end

end

app/models/stream_codes.rb
class StreamCodes < ApplicationRecord
end

app/models/testimonial.rb
class Testimonial < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise :omniauthable, omniauth_providers: %i[facebook]

  has_many :testimonials

  enum type: [
    'User::Admin',
    'User::Member',
    'User::Subscriber'
  ]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name   # assuming the user model has a name

    end
  end

  def customer_id
    JSON.parse(customer_info)['id'] if customer_info.present?
  end

  def cc
    JSON.parse(card_info)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController


    def index
    end

    def create
    end

    def new
    end

    def edit
    end

    def show
    end

    def update
    end

    def destroy
    end
    

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    def index
        @articles = Article.where(hidden: false)
    end

    def show
        @article = Article.find(params[:id])

        # User clicked on a premium article
        if @article.premium
            # Direct them to user registration if they are not signed in
            unless user_signed_in?
                flash[:alert] = "Sign in to your premium account to view the full article"
                redirect_to :new_user_session
                return
            end

            # TODO: If they are logged in but not a member, redirect to User type control panel
            if current_user.type == 'User::Subscriber'
                flash[:alert] = "This is a premium members only article - please purchase a membership to read the whole article"
                redirect_to :root
            end
        end

    end
    
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
    before_action :authenticate_user!
    skip_before_action :verify_authenticity_token

    def dashboard
    end

    def upgrade_form
        redirect_to :profile if current_user.type == 'User::Member' 
    end

    # Post
    def upgrade
        user = current_user

        customer = {
            name: user.name,
            email_address: user.email
        }

        card = {
            billing_address: {
                address_line_1: params[:address_line_1],
                address_line_2: params[:address_line_2],
                locality: params[:locality],
                administrative_district_level_1: params[:administrative_district_level_1],
                postal_code: params[:postal_code],
                country: params[:country],
            },
            cardholder_name: params[:cardholder_name],
            card_nonce: params[:nonce]
        }
        
        # { customer_info: json, card_info: json }
        customer_data = Membership::Premium.upgrade_user(customer, card)
        
        user.update(customer_data)

        render json: { success: true, message: 'Membership Enrollment Successful' }
    rescue => e
        render json: { success: false, message: e.message }
    end
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @testimonials = Testimonial.where(visible: true)
  end

  def create
    Testimonial.create(content: params[:content], visible: false, user_id: current_user.id)

    flash[:alert] = "Thank you for posting a testimonial! Look for it up on the Testimonials page sometime soon!"
    redirect_to :root
  end

  def new
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    before_action :authenticate_member, only: :stream

    def index
        if signed_in?
            @user = current_user
        end

        @show_modal = true unless session[:cookies_confirm]

        session[:cookies_confirm] = true

    end
    
    def services
    end

    def about
    end

    def privacy

    end

    def contact
    end

    def stream
        @video_url = StreamCodes.last&.code
    end
    

    def authenticate_member
        return redirect_to new_user_session_path unless signed_in?

        unless ['User::Admin', 'User::Member'].include?(current_user.type)
            flash[:alert] = "You must be a member to view the live stream"
            redirect_to :root
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
    def user_type(user)
        user.type.split('::')[1].capitalize
    end
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_navbar.html.erb
<% if signed_in? %>


Signed in as <%= @user.name || @user.email %>

<% else %>
<div>
<marquee direction=left scrolldelay=100 hspace=150 vspan=25><span>Welcome to C-Wings, please Sign in/up</span></marquee>
</div>
<% end %>

app/views/layouts/admin.html.erb
<% content_for :navbar do %>
    <%= render 'layouts/admin/navbar' %>
<% end %>

<%= render template: "layouts/application" %>

app/views/layouts/admin/_navbar.html.erb
Admin navbar

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Compassionate Wings</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Nova+Script|Petit+Formal+Script&display=swap" rel="stylesheet">
  </head>

  <body>

    <div class="container" id="main">

    <div class="layout-topbar">

		<img src="/images/cw_logo2.jpg" alt="logo" width="200"

      height="80" />
      <%= yield :navbar %>
      <p class="btn btn-outline-info" style="margin:10px; height: 5vh">
      <%= link_to('PROFILE', profile_path())%>
      </p>
		<ul class="top-info" style="padding: 20px">
            <li class="top-item">
            <%= link_to('Home', root_path())%>
            </li>
            <li class="top-item">
            <%= link_to('About', about_path())%>
            </li>
            <li class="top-item">
            <%= link_to 'Services', services_path %><br>
            </li>
            <li class="top-item">
            <%= link_to 'Stream', stream_path %>
            </li>
            <li class="top-item">
            <%= link_to 'Sign in', new_user_session_path %>
            </li>
            <li class="top-item">
            <%= link_to 'Sign up', new_user_registration_path %>
            </li>
            <li class="top-item">
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
            </li>

		</ul>
</div>
      <div class="jumbotron">
          <h1 id="home-title">Compassionate Wings</h1>
      </div>
      <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>


    
    <br>
    <%= yield %>
    
    </div>
    <footer class="bg-dark text-white mt-4">
    <div class="container-fluid py-3">
        <div class="row">
            <div class="col-md-3">
                <h5>Developers</h5></div>
            <div class="col-md-3"></div>
            <div class="col-md-3"></div>
            <div class="col-md-3"></div>
        </div>
        <div class="row">
            <div class="col-md-6">
            Jason | Joey | Tiga | JiaYing | JiaHao
            <span class="small"><br>
            Algonquin College Team 6
            </span></div>
            <div class="col-md-3"></div>
            <div class="col-md-3 text-right small align-self-end">©2019 Brand, Inc. <%= link_to 'Privacy Policy', privacy_path %></div>
        </div>
    </div>
</footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


<script>

</script>

    <script>
      <%= yield :scripts %>
    </script>
  </body>
</html>